export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const CATEGORY_MAIN_FIELD = 'CATEGORY_MAIN_FIELD';
export const CATEGORY_SUB_FIELD = 'CATEGORY_SUB_FIELD';

export const REQUEST_ITEMS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ITEMS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ITEMS_FAILED = 'REQUEST_ROBOTS_FAILED';